name: Test_demoqa
on: push

jobs:
  test_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'
      - name: Google
        run: sudo apt-get install firefox
      - name: requirements
        run: pip install -r requirements.txt
      - name: Run test
        run: pytest
